apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}
          env:
            - name: ME_CONFIG_SITE_COOKIESECRET
              valueFrom:
                secretKeyRef:
                  key: cookie_key
                  name: mongo-secret
                  optional: true
            - name: ME_CONFIG_SITE_SESSIONSECRET
              valueFrom:
                secretKeyRef:
                  key: session_key
                  name: mongo-secret
                  optional: true
            - name: ME_CONFIG_SITE_BASEURL
              value: '/'
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: 'true'
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: 'admin'
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: 'pass'
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: 'root'
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db
                  key: mongodb-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              value: "{{ .Release.Name }}-db.{{ .Release.Namespace }}.svc.cluster.local"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
# Google helm create secret if not exists
# found https://stackoverflow.com/a/61715870/2535649
# links to https://github.com/sankalp-r/helm-charts-examples/blob/main/sample_chart/templates/_helpers.tpl
kind: Secret
apiVersion: v1
metadata:
  name: mongo-secret
data:
  {{- $secret := lookup "v1" "Secret" .Release.Namespace "mongo-secret" -}}
    {{- if $secret -}} {{/*                        Reusing existing password if secret was found... */}}
    cookie_key: {{ $secret.data.cookie_key }}
    session_key: {{ $secret.data.session_key }}
    {{- else -}} {{/*                               ... otherwise, generate a random password.      */}}
    cookie_key: {{ randAlphaNum 32 | b64enc }}
    session_key: {{ randAlphaNum 32 | b64enc }}
    {{- end -}}
