apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $.Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Release.Name }}
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - jskw.dev
        - '*.jskw.dev'
      secretName: wild-jskw-dev
